if status is-interactive

# ALIASES
alias ls='eza --icons=always --color=always'
alias ll='ls -al'
alias vpn-connect='sudo protonvpn connect -f'
alias vpn-disconnect='sudo protonvpn disconnect'
alias vpn-reconnect='sudo protonvpn reconnect'
alias vpn-status='sudo protonvpn status'
alias r3boot='~/src/Scripts/r3boot.sh'
alias powerOff='~/src/Scripts/power0ff.sh'
alias hyprarch2='/usr/bin/git --git-dir=$HOME/.hyprarch2/ --work-tree=$HOME'
alias libvirtStop='~/src/Scripts/libvirtStop.sh'
alias hyprpush='hyprarch2 push --set-upstream git@github.com:g5ostXa/hyprarch2.git master'
alias hyprstatus='hyprarch2 status' 
alias fire='sudo firecfg'
alias unfire='sudo firecfg --clean'
alias firetop='firejail --top'
alias ff='fastfetch'
alias clean='~/src/Scripts/cleanup.sh'
alias errcheck='~/src/Scripts/checkerrors.sh'
alias cw='cliphist wipe'
alias hyprlist='~/src/Scripts/hyprlist.sh'
alias killhypr='~/src/Scripts/killhypr.sh'
end
