format = """
[░▒▓](#1d2230)\
[ ](bg:#1d2230 fg:#FFFFFF)\
$directory\
$git_branch\
$git_status\
$time\
[ ](fg:#1d2230)\
\n$character"""

[character]
disabled = true
success_symbol = '[](yellow)'
error_symbol = '[](bold red)'
vimcmd_symbol = '[](bold green)'
vimcmd_replace_one_symbol = '[](bold purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold green)'

[directory]
style = "fg:#FFFFFF bg:#1D2230"
format = "[ $path ]($style)"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[line_break]
disabled = false

[git_branch]
symbol = ""
style = "bg:#1D2230"
format = '[[ $symbol $branch ](fg:#FFFFFF bg:#1D2230)]($style)'

[git_status]
style = "bg:#1D2230"
format = '[[($all_status$ahead_behind )](fg:#FFFFFF bg:#1D2230)]($style)'

[nodejs]
symbol = ""
style = "bg:#1D2230"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1D2230)]($style)'

[rust]
symbol = ""
style = "bg:#1D2230"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1D2230)]($style)'

[golang]
symbol = ""
style = "bg:#1D2230"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1D2230)]($style)'

[php]
symbol = ""
style = "bg:#1D2230"
format = '[[ $symbol ($version) ](fg:#769ff0 bg:#1D2230)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'
